#!/bin/sh

if [ $# -lt 2 ]; then
	echo "[${0##*/}] Usage: $0 <update-dir> <update-package> [options]"
	exit 1
fi

echo "Starting ${0##*/} $@"

echo "Creating tempdir"
tmp_dir=$(mktemp -d $1/XXXXXX)
cd $tmp_dir

echo "Untaring $2 to $tmp_dir"
tar zxvf $2

echo "Shifting options"
shift 2

echo "Calling ofgwrite $@ $tmp_dir"
ofgwrite $@ $tmp_dir
